force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/IATA_Code__c.field-meta.xml
<CustomField>
    <fullName>IATA_Code__c</fullName>
    <label>IATA_Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    

    public static void createTestAirports() {
        Airport__c newAirport1 = new Airport__c(
            IATA_Code__c = 'LCJ',
            Location__Latitude__s = 19.4666700,
            Location__Longitude__s = 51.750000, 
            Name = 'Łódź'
        );
        Airport__c newAirport2 = new Airport__c(
            IATA_Code__c = 'RDO',
            Location__Latitude__s = 21.213611,
            Location__Longitude__s = 51.389167, 
            Name = 'Radom'
        );
        Airport__c newAirport3 = new Airport__c(
            IATA_Code__c = 'LIZ',
            Location__Latitude__s = 14.213611,
            Location__Longitude__s = 4.389167, 
            Name = 'Lizbon'
        );
        List<Airport__c> airports = new List<Airport__c>{ newAirport1, newAirport2, newAirport3 };
        insert airports;
    }
}