force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/IATA_Code__c.field-meta.xml
<CustomField>
    <fullName>IATA_Code__c</fullName>
    <label>IATA_Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FlightCreatorControllerTest.cls
@isTest
public with sharing class FlightCreatorControllerTest {
    
    @TestSetup
    static void setupData() {
        TestDataFactory.createTestAirports();
    }

    @isTest
    public static void calculateAndSaveNewFlightTest() {
        List<Airport__c> airports = [SELECT Id, Location__Latitude__s, Location__Longitude__s, Name,IATA_Code__c FROM Airport__c ORDER BY Name DESC];

        Test.startTest();
        Flight_Factory resultFlight = FlightCreatorController.calculateAndSaveNewFlight(airports[0].IATA_Code__c, airports[1].IATA_Code__c);
        Test.stopTest();

        System.assert(resultFlight.Name == 'Łódź-Radom');
        System.assert(resultFlight.departureAirportName == airports[0].Name);
        System.assert(resultFlight.arrivalAirportName == airports[1].Name);
    }
    @isTest
    public static void calculateAndSaveFlightAirportNullErrorTest() {
        List<Airport__c> airports = [SELECT Id, IATA_Code__c FROM Airport__c ORDER BY Name DESC LIMIT 1];
        Flight_Factory resultFlight;
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            resultFlight = FlightCreatorController.calculateAndSaveNewFlight(airports[0].IATA_Code__c, airports[1].IATA_Code__c);
        } catch(Exception e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        System.assert(exceptionThrown);
    }
    @isTest
    public static void getAllAirportsTest(){
        
        Test.startTest();
        List<Airport__c> allAirports = FlightCreatorController.getAllAirports();
        Test.stopTest();

        System.assertEquals(3, allAirports.size());
    }
}