force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/IATA_Code__c.field-meta.xml
<CustomField>
    <fullName>IATA_Code__c</fullName>
    <label>IATA_Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Flight__c/fields/ArrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>ArrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ArrivalAirport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (ArrivalAirport)</relationshipLabel>
    <relationshipName>FlightsTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/DepartureAirport__c.field-meta.xml
<CustomField>
    <fullName>DepartureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DepartureAirport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlightTriggerHandlerTest.cls
@isTest
public with sharing class FlightTriggerHandlerTest {
    
    @TestSetup
    static void setupData() {
        TestDataFactory.createTestAirports();
        FlightCreatorController.calculateAndSaveNewFlight('LCJ','RDO');
    }
    @isTest
    public static void updateTest(){
        Flight__c flight = [SELECT Id, ArrivalAirport__c, DepartureAirport__c, Distance__c FROM Flight__c LIMIT 1];
        Airport__c airport = [SELECT Id FROM Airport__c WHERE IATA_Code__c = :'LIZ'];

        Decimal initialDistance = flight.Distance__c;
        flight.ArrivalAirport__c = airport.Id;
        Test.startTest();
        update flight;
        Test.stopTest();

        Flight__c flightAfter = [SELECT Id, ArrivalAirport__c, DepartureAirport__c, Distance__c FROM Flight__c LIMIT 1];

        System.assertEquals(flightAfter.ArrivalAirport__c, airport.Id);
        System.assertNotEquals(initialDistance, flightAfter.Distance__c);
    }
}